### ISSUE TITLE
.NET Framework retarget

### ISSUE THREAD

**Issue by AleksandarDev** [Enterwell/Wpf.Notifications#12]
"Hello, please modify the project's framework from 4.6 to 4.5." https://github.com/Enterwell/Wpf.Notifications/pull/11#issuecomment-386073131

@ghost1372 Microsoft doesn't support [.NET 4.5 since Jan. 2016](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/). We could retarget 4.5.2 if you want.

**Comment by ghost1372** [comment]
Oh do that, If nothing goes wrong

**Comment by AleksandarDev** [comment]
@ghost1372 We already target `.NET 4.5.1` not `.NET 4.6` like you suggested in comment.
