### ISSUE TITLE
[Enhancement] Icon / Image Area

### ISSUE THREAD

**Issue by amkuchta** [Enterwell/Wpf.Notifications#18]
While the badges are useful, users may also want to include some sort of icon or image alongside or instead of the badge to denote the control's meaning (e.g. an exclamation point instead of "Warning" text).  My proposed solution is to include a `ContentControl` that sits to the left of the badge in an Auto-sixing column that would allow users to insert a graphic (e.g. and icon or perhaps a logged-in user image).

If it's agreed upon, I will mock it up and submit a PR for approval.

**Comment by AleksandarDev** [comment]
Sorry for late response. Sound good to me 👍
