### ISSUE TITLE
Error while installing the package from nuget.

### ISSUE THREAD

**Issue by goyalsachin22** [Enterwell/Wpf.Notifications#2]
PM> Install-Package Enterwell.Clients.Wpf.Notifications
Installing 'Enterwell.Clients.Wpf.Notifications 1.0.0'.
Successfully installed 'Enterwell.Clients.Wpf.Notifications 1.0.0'.
Adding 'Enterwell.Clients.Wpf.Notifications 1.0.0' to UINotifications.
Uninstalling 'Enterwell.Clients.Wpf.Notifications 1.0.0'.
Successfully uninstalled 'Enterwell.Clients.Wpf.Notifications 1.0.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'Enterwell.Clients.Wpf.Notifications 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references 
or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Enterwell.Clients.Wpf.Notifications
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by AleksandarDev** [comment]
This is a .NET 4.5.1 package. You need project with .NET Framework >= 4.5.1
