### ISSUE TITLE
Change text color

### ISSUE THREAD

**Issue by filipjelic** [Enterwell/Wpf.Notifications#4]
How can I change the text color? 
It's all okay when the colors are darker, but if I want to replace them, white background lets say?

**Comment by AleksandarDev** [comment]
Only the dark theme is provided by this package. You can override the default theme using existing templates available here:

https://github.com/Enterwell/Wpf.Notifications/blob/master/Enterwell.Clients.Wpf.Notifications/Themes/Generic.xaml

You can also inherit Controls classes and implement custom `INotificationMessageFactory` to further expand on existing message properties.
