### ISSUE TITLE
change progressbar value

### ISSUE THREAD

**Issue by ghost1372** [Enterwell/Wpf.Notifications#9]
hi how i can update my progressbar value?
i have this but i cant update value after that.
```
.WithOverlay(new ProgressBar
               {
                   VerticalAlignment = VerticalAlignment.Bottom,
                   HorizontalAlignment = HorizontalAlignment.Stretch,
                   Height = 3,
                   BorderThickness = new Thickness(0),
                   Foreground = new SolidColorBrush(Color.FromArgb(128, 255, 255, 255)),
                   Background = Brushes.Transparent,
                   IsIndeterminate = false,
                   IsHitTestVisible = false,
                   Value = 25
               })
```

**Comment by AleksandarDev** [comment]
You would need to instantiate the progress bar prior to message. That way you can access it after you'we created/shown the message. 

    var progressBar = new ProgressBar
    {
         VerticalAlignment = VerticalAlignment.Bottom,
         HorizontalAlignment = HorizontalAlignment.Stretch,
         Height = 3,
         BorderThickness = new Thickness(0),
         Foreground = new SolidColorBrush(Color.FromArgb(128, 255, 255, 255)),
         Background = Brushes.Transparent,
         IsIndeterminate = false,
         IsHitTestVisible = false,
         Value = 25
     };

    ...
  
    .WithOverlay(progressBar)

    ...

    progressBar.Value = 100

Alternative would be creating custom NotificationMessage and NotificationMessageFactory that has the progress bar as part of the class.

**Comment by AleksandarDev** [comment]
@ghost1372 Did you manage to solve your problem?

**Comment by ghost1372** [comment]
@AleksandarDev  oh yes tnx for your help
